### ISSUE TITLE
Ghost instance is not currently running

### ISSUE THREAD

**Issue by baram204** [docker-library/ghost#115]
Inside running ghost container, Ghost-CLI tells me that
"Ghost instance is not currently running".

Yes, Ghost is runs well now. I can connect and edit stories.

## symptoms

```bash
root@f2952e9c1b50:/var/lib/ghost# ghost restart
An error occurred.
Message: 'Ghost instance is not currently running.'


Debug Information:
    Node Version: v6.12.2
    Ghost-CLI Version: 1.4.1
    Environment: production
    Command: 'ghost restart'

Additional log info available in: /root/.ghost/logs/ghost-cli-debug-2017-12-21T06_25_28_165Z.log

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
root@f2952e9c1b50:/var/lib/ghost#
```

Yes, But Ghost blog works well. log prove my word.

```bash
root@f2952e9c1b50:/var/lib/ghost# ghost log
INFO [2017-12-21 05:42:24] "PUT /ghost/api/v0.1/posts/5a3b47ea145b5f000188ab3a/?include=tags" 200 391ms
......
INFO [2017-12-21 06:07:19] "GET /rss/" 200 722ms
root@f2952e9c1b50:/var/lib/ghost#
```

Yes, but, ghost ls tells me no ghost instance running on my container. 

```bash
root@f2952e9c1b50:/var/lib/ghost# ghost ls
┌──────┬──────────┬─────────┬────────┬─────┬──────┬───────┐
│ Name │ Location │ Version │ Status │ URL │ Port │ Process Manager │
└──────┴──────────┴─────────┴────────┴─────┴──────┴───────┘
root@f2952e9c1b50:/var/lib/ghost#
```

I'm confused.
I just want to change config file and restart Ghost safely.
what can i do for it?

**Comment by SISheogorath** [comment]
To restart ghost, you simply restart your container using `docker restart <containername/id>`.

Keep in mind that you should configure your ghost instances using environment variables when using docker, not the config file.

So when using the environment variables you need to recreate the container.

---

To answer your question why ghost CLI says that:

Ghost CLI uses an own task scheduling service. But the docker container directly run the ghost server from the index.js file using nodejs. No scheduler or similar involved. Keep in mind that docker itself is some kind of scheduler or even more a management engine for the container which should only run one process.

And since ghost doesn't expect that, it tells you it's not running.

Hint: *Running ghost in docker differs a lot from what you use when you run it in a native setup. Make sure you are familiar with docker when you want to use it. Especially with topics like persisting data while using docker containers. Otherwise you may end up with a lost database because of wrong configs.*

**Comment by baram204** [comment]
@SISheogorath Thank you!  OK.
