### ISSUE TITLE
Ghost's memory usage is spooky

### ISSUE THREAD

**Issue by karai17** [docker-library/ghost#121]
I have a VPS running three Ghost blogs in Docker and the memory usage is unbounded. My original VPS was 512mb RAM and Docker would actually crash containers due to inability to keep them alive (only three!). I've since upgraded to 2GB of RAM and Ghost/Node is still reaching about 95% memory usage before doing a garbage collection.

Is there a way I can configure this to be a bit more aggressive?

![image](https://user-images.githubusercontent.com/590332/35024410-aa05f862-fb15-11e7-894f-2e990744d0cd.png)

**Comment by karai17** [comment]
In fact, I noticed that my CPU spike issue and disk read spike also happen during the garbage collection...

![image](https://user-images.githubusercontent.com/590332/35024490-1ae30f8e-fb16-11e7-96e7-4e66294f7a2b.png)

**Comment by yosifkit** [comment]
I'n not sure why `dockerd` is using 100%+ cpu. :confused: 

As for memory usage, the ghost recommendation is [1 GB](https://docs.ghost.org/docs/hosting) for a single instance, so I could see why three running on one machine of 512 MB might have an conflict.

As for forcing garbage collection, I think that is a general `node` issue and not anything specific to the ghost Docker image.  Maybe try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)?

**Comment by karai17** [comment]
Well it seems to occur when node does a garbage collection run. I'm just wondering if there is a way I can tinker with node's configuration from within the Ghost image since it might be helpful to be more aggressive with garbage collection.

I've also looked all over for this dockerd issue including asking Digital Ocean support but no one seems to have a definitive answer.

**Comment by qedrakmar** [comment]
Since this appears to be a configuration tweaking question, and not an actual image issue, I am closing this.

As @yosifkit pointed out, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or Docker topic of [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  For this particular question, however, you'll probably have the most luck in the ghost topic of [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=ghost).

In the meantime, if you're going to dig into tweaking this, you should find all the relevant js inside the container under /var/lib/ghost/versions/[VersionNumber].  Good luck.
