### ISSUE TITLE
config json not stored in GHOST_CONTENT, lost on reboot

### ISSUE THREAD

**Issue by jglesner** [docker-library/ghost#124]
I expected to see (and don't see) that the config json (both development and production) would live in GHOST_CONTENT, not GHOST_INSTALL.  On initial load of the container, all content is written to my volume, but the config json isn't there.  Noticed this when I was going to do the initial mail configuration.  So, unless I'm incorrect in my interpretation of the dockerfile and entrypoint shell (I'm not the best at bash), the config won't survive a container restart.  Not sure why anyone would want that?

Also, unlike using 'npm start --production' in my docker run command prior to 1.0, it appears we should now use an environment variable to start this container in production.  Is that right?

**Comment by acburdine** [comment]
@jglesner this was an intentional change - Ghost 1.0 is able to be configured entirely [with environment variables](https://docs.ghost.org/v1/docs/config#section-running-ghost-with-config-env-variables), so instead of a json config in the content folder, the environment variables should be used to configure Ghost.

As far as environment goes, `npm start --production` was essentially a shortcut for `NODE_ENV=production node index.js`, so setting the NODE_ENV env variable to production will achieve the same result.

Going to close this issue as it was an intentional change and isn't a bug.
