### ISSUE TITLE
sudo not packed with ghost:latest

### ISSUE THREAD

**Issue by loasishospitality** [docker-library/ghost#156]
**ghost setup returns**
```
✖ Setting up "ghost" system user
An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  chown -R ghost:ghost /var/lib/ghost/content
/bin/sh: 1: sudo: not found
```

**sudo command returns not found**

Tried with both latest and alpine

**Comment by tianon** [comment]
@acburdine I'm not familiar with `ghost setup` -- is that a command that makes sense for this image to support out of the box?

**Comment by loasishospitality** [comment]
ghost setup is a command of ghost-cli to manage ghost installation, this command is mostly used at install time - I am not sure whether it is pertinent for it to work in production.

Yet same kind of issue happens with ghost doctor - Maybe more useful in production ?
```
One or more errors occurred.
1) ProcessError
Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_undefined
/bin/sh: 1: sudo: not found
```

The main pitfall of not packing sudo is ghost-cli doesn't allow to run as root user ...

I prefer to refer to a more experienced ghost administrator to know if ghost-cli is necessary/useful for production

**Comment by acburdine** [comment]
@loasishospitality sorry for the delayed response.

The ghost docker image and `ghost-cli` serve mostly separate goals. Ghost-CLI is intended to setup a traditional environment (e.g. a normal VPS w/o Docker), which means it is designed to configure nginx, mysql, and all of the other things needed to get Ghost running from scratch. The Docker image, however, is intended to package Ghost on its own (following the "one process per container" model) so that it can interact with other similarly designed containers (e.g. the official 'nginx' and 'mysql' containers). So, `ghost setup` itself really isn't needed because the docker image comes already set up, with the caveat being that you have to manually configure the interaction between Ghost and the other things (nginx, mysql) necessary to run a production Ghost install.

While the docker image _does_ have ghost-cli available and does use some of its commands to set up the base Ghost image, many of the other ghost-cli commands won't work correctly, and really aren't designed/intended to.

**Comment by loasishospitality** [comment]
Thank you for clarification on this matter and all respect for this helpful and time saving package !

**Comment by tianon** [comment]
I wonder if it's worth updating the docs with a short blurb that references this very well worded clarification. 😅❤️
