### ISSUE TITLE
Speed up Docker build

### ISSUE THREAD

**Issue by kennethlimcp** [docker-library/ghost#17]
Would it be faster if we split the installation of Build deps into a `RUN` and another for the `curl` of lates Ghost version?

https://github.com/docker-library/ghost/blob/master/Dockerfile#L33

The current setup is ok but builds a little slowly for mine on an armhf device. Just though it might be worth discussing/bringing this up as an improvement!

**Comment by tianon** [comment]
We do it this way because the build dependencies aren't required for
running ghost, so separating them out just makes the image larger for no
reason (since most people are pulling this image, not building it).

**Comment by kennethlimcp** [comment]
@tianon thanks! Something new for me :) I would need to go learn more about Docker but that's a useful tool that i'm using more frequently !

**Comment by kennethlimcp** [comment]
@tianon since we are on this topic (not the best place to ask), how does more command lead to a larger image? Anywhere i can read more about this?

**Comment by tianon** [comment]
https://docs.docker.com/docker/introduction/understanding-docker/#how-does-a-docker-image-work talks about it a bit -- basically, each command creates a new layer, and each of these layers is isolated from the previous layers (and thus removing something in a later layer cannot affect the size of the previous layer, since the image layers themselves are stacked and immutable).
