### ISSUE TITLE
I had some problems when I used docker

### ISSUE THREAD

**Issue by panda-lin** [docker-library/ghost#181]
```
docker logs <container_id>
tar: themes/casper: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
```
and my host is win10

**Comment by wglambert** [comment]
Looks like an incompatibility of sorts with Windows
https://github.com/docker-library/ghost/issues/69#issuecomment-319946646
https://forum.ghost.org/t/docker-containers-using-windows-lcow-not-linux-containers-on-windows/4211

LCOW has some issues with bindmounting to Linux containers
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#bind-mounts

If you have further questions you could try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
