### ISSUE TITLE
Very stupid design 

### ISSUE THREAD

**Issue by xingzheone** [docker-library/ghost#197]
````
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
````

just allow  -v /var/lib/ghost/content ???  why not allowed /var/lib/ghost

now 

docker exec -it ghost bash  
apt-get update  
apt-get install vim  
vim config.production.json  ????  cao!

**Comment by wglambert** [comment]
I see you've searched your issue and found https://github.com/docker-library/ghost/issues/155
Your issue isn't unique to the Docker image, I get the frustration but the change in directory from `/var/lib/ghost` to `/var/lib/ghost/content` is an upstream change that we faithfully include.

We included a section in the image's [documentation](https://github.com/docker-library/docs/tree/master/ghost#stateful) about this change and users really should read image documentation for a good overview. With that I'm going to close the issue since we're not inclined to change anything in the image that would conflict with upstream.
