### ISSUE TITLE
Ghost forcing a redirect to https

### ISSUE THREAD

**Issue by AlexKalopsia** [docker-library/ghost#204]
Hi,

I have Ghost running on reverse proxy on my Synology NAS. 

When I go to `ghost.mydomain.com` I am correctly pointed to Ghost (myip:2368)

The problem is that if I manually go to `https://myip:2368`, I am automatically redirected to `https://myip` which results in the page landing on the Synology DSM. 

Ghost is the only container that has this issue, I am wondering if I might be doing something wrong or if this is a somewhat default behavior. I recently updated my Ghost image to the latest, and I did not have this issue before.

**Comment by wglambert** [comment]
Ghost doesn't even support ssl so this seems like it could be a browser redirect to https
https://github.com/docker-library/ghost/issues/165#issuecomment-440852132

- `From what I can find (both by playing with ghost setup ssl, and by exploring the Ghost documentation), Ghost itself doesn't actually support SSL directly, and instead they recommend (and their tools can help configure) terminating SSL in a reverse proxy like NGINX or Apache, which seems pretty reasonable (especially for a production deployment, where you likely want a reverse proxy in front of Node.js anyhow).`

I would recommend asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
