### ISSUE TITLE
Ghost 4.22 crashes during startup with a read-only container

### ISSUE THREAD

**Issue by groundhog2k** [docker-library/ghost#271]
Description:

I'm using Ghost in a container (Kubernetes) environment and for better security all containers must run as non-root user and with read-only permissions in this environment.
An upgrade from Ghost 4.21 to 4.22 was not possible. The container crashes during startup with following exception:
```
[2021-11-11 11:16:42] ERROR EROFS: read-only file system, unlink '/var/lib/ghost/versions/4.22.0/core/frontend/public/cards.min.css'

EROFS: read-only file system, unlink '/var/lib/ghost/versions/4.22.0/core/frontend/public/cards.min.css'

Error ID:
    d929b720-42e0-11ec-9323-f74cb84b376c

Error Code:
    EROFS
```

How to reproduce:

It is easy to reproduce on a local docker environment.
Create a folder for the Ghost content and mount that to a read-only container of Ghost 4.21:

```
mkdir content421
docker run -d --name ghost421 --read-only -e url=http://localhost:2368 -p 2368:2368 -v ${PWD}/content421:/var/lib/ghost/content ghost:4.21.0
```

Ghost 4.21.0 will start up without problems and web should be reachable under http://localhost:2368.

Kill the container to free TCP port 2368:
``docker kill ghost421`` 

Doing the same for Ghost 4.22.0 will show the error described above:
```
mkdir content422
docker run --name ghost422 -d --read-only -e url=http://localhost:2368 -p 2368:2368 -v ${PWD}/content422:/var/lib/ghost/content ghost:4.22.0
```

Ghost tries to create/access some file outside of the mounted content-folder during startup of V4.22 -- That was not the case with V4.21.

Please analyze and fix!

**Comment by wglambert** [comment]
I'm not sure if "read-only filesystem" is a feature Ghost offers, I'd see if the upstream project has more insight into this https://github.com/TryGhost/Ghost since we only maintain the containerized version of Ghost and aren't affiliated with its development or featureset

If it supports a read-only filesystem outside of a container environment then we could see where the containerized version differs in that regard but otherwise this seems like a side-effect of a code change upstream so I'm not sure if there's anything actionable we could do to remedy it

**Comment by daniellockyer** [comment]
Hi! 👋🏻 Although I haven't tested, the latest version of Ghost shouldn't have this problem and the issue can be closed.

We had an [issue](https://github.com/TryGhost/Ghost/issues/13739) where we dynamically wrote files to the code folder during runtime, which breaks when the container is read-only. Our fix was to change the destination file to the `content/public` folder. 🙂

**Comment by groundhog2k** [comment]
Yes.. I can confirm the bug is gone - Tested with Ghost 4.34.x
Thank you!
