### ISSUE TITLE
Instantly crashes when trying to specifically upload pictures - Alpine only

### ISSUE THREAD

**Issue by hugoprudente** [docker-library/ghost#284]
This regression is back #267 using the `ghost:3.42.9-alpine`

```
  ghost:api:shared:pipeline stages: input serialisation +20ms
  ghost:api:shared:serializers:handle input +10s
  ghost:api:shared:serializers:handle [ [Function: serializeAllShared], [Function: serializeOptionsShared] ] +0ms
  ghost:api:shared:serializers:input:all serialize all +11s
  ghost:api:shared:serializers:input:all omit internal options +0ms
  ghost:api:v3:utils:serializers:input:posts edit +11s
  ghost:api:v3:utils:serializers:input:posts add +0ms
  ghost:api:shared:pipeline stages: permissions +5ms
  ghost:api:v3:utils:permissions handle +11s
  ghost:api:v3:utils:permissions check admin permissions +0ms
  ghost:web:shared:mw:url-redirects getAdminRedirectUrl localhost:2368 /ghost/api/v3/admin/images/upload/ localhost:2368 localhost:2368 +75ms
  ghost:web:shared:mw:url-redirects no url redirect +0ms
  ghost:api:shared:pipeline stages: query +73ms
  ghost:models:plugins:filter custom (status:[draft,published,scheduled])+type:post +11s
  ghost:models:plugins:filter extra null +0ms
  ghost:models:plugins:filter enforced null +0ms
  ghost:models:plugins:filter default type:post+status:published +0ms
Segmentation fault
/var/lib/ghost #
```

Disabling it to `imageOptimization`  fix the issue.

```
    "imageOptimization": {
        "resize": false
    },
```

It may need to upgrade the libs-dev underlying as one of the threads here TryGhost/Ghost#12967

**Comment by wglambert** [comment]
Sorry for the late reply getting to this. That specific version `ghost:3.42.9-alpine` isn't currently supported, but testing the latest `alpine` variant I'm not able to reproduce any issue (although I did test it with that version and the issue is present, uploading an image just crashes the container with `exit 139`)

Using the latest Alpine and [Debian](https://github.com/docker-library/ghost/issues/295#issuecomment-1078264840) variants works fine with the `docker-compose.yml` from https://github.com/docker-library/docs/tree/master/ghost#-via-docker-stack-deploy-or-docker-compose and switching the image to the latest Alpine variant
![image](https://user-images.githubusercontent.com/26428991/167508169-95dc1433-f120-4988-926c-606a25f84a52.png)
