### ISSUE TITLE
Unable to upload images.

### ISSUE THREAD

**Issue by CHeGIVaRO** [docker-library/ghost#295]
Hi!

When upload any images (post, logo an etc.), printing the error "Request was rejected due to server error".
Container reloaded per try to upload, without any errors in "docker logs".
I am tried different params for chmod and chown, anything don't help me.

My docker-compose file:
  blog_ghost:
    image: ghost
    ports:
      - 8989:2368
    depends_on:
      - mariadb
    environment:
      url: https://exaple.site
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: DB_NAME
      database__connection__password: secure_password
      database__connection__database: USER
    restart: always
    volumes:
      - /storage/blog_ghost:/var/lib/ghost/content/

![изображение](https://user-images.githubusercontent.com/21368229/159998558-e67679ce-45cc-45bd-addc-94b41bc30880.png)

P.S. Please help me =)

**Comment by wglambert** [comment]
I just did it with "Try in PWD" https://github.com/docker-library/docs/tree/master/ghost#-via-docker-stack-deploy-or-docker-compose
And I'm not able to reproduce

![image](https://user-images.githubusercontent.com/26428991/160006958-6a621ff3-1d03-43de-8da7-02ee4d2470b7.png)

Since you already adjusted volume permissions and with nothing in the logs about your error maybe it's something with the host environment like resource constraints.
Could you show the permissions of `/var/lib/ghost/content/` in the container and the log output when uploading an image?

You might also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

**Comment by CHeGIVaRO** [comment]
![image](https://user-images.githubusercontent.com/21368229/160064914-7634b94e-725d-440c-bbc9-e89725cb13e3.png)
In error.log nothing, empty file.
In .log this messages:
![image](https://user-images.githubusercontent.com/21368229/160065222-58a61721-94ca-4da4-87a2-2597893e8aa6.png)

**Comment by CHeGIVaRO** [comment]
I tried to build the container on the 4.3.3 version of the image. It works fine and the images are uploaded.

**Comment by pascalandy** [comment]
Should be closed :-p

**Comment by asbjornenge** [comment]
I'm seeing this problem with the latest 5.7.0 builds, but alpine and non-alpine images 🤔 🤷 

Is there a way to activate debug logging for the docker images via an ENV var or something?

**Comment by tianon** [comment]
I bet you want something like `logging__level=debug`, but I'm only guessing (https://ghost.org/docs/config/#logging). :sweat_smile:

**Comment by alek-p** [comment]
I have an old CPU but was able to get around this error by setting `imageOptimization__resize: "false"`. See https://ghost.org/docs/config/#image-optimisation
