### ISSUE TITLE
Ghost wont start. Error -13

### ISSUE THREAD

**Issue by motey** [docker-library/ghost#322]
This is just for future miserables running in the same error.
```
version: '3.7'

services:

  ghost:
    image: ghost:5-alpine
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./content:/var/lib/ghost/content
     environment:
      - database__client=mysql
      - database__connection__host=xxx
      - database__connection__password=xxx
      - database__connection__database=ghost
      - server__port=80

  db:
    image: mysql:8.0.29
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
```

This resulted a crashing container for me

```
[2022-08-01 14:17:04] ERROR (Code: -13)
(Code: -13)
"There was an error starting your server."
"Please use the error code above to search for a solution."
Error ID:
9df9b590-11a4-11ed-9b15-750c8219e89a
----------------------------------------
InternalServerError: (Code: -13)
at Server.<anonymous> (/var/lib/ghost/versions/5.5.0/core/server/ghost-server.js:95:34)
at Server.emit (node:events:527:28)
at emitErrorNT (node:net:1399:8)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-08-01 14:17:04] WARN Ghost is shutting down
[2022-08-01 14:17:04] WARN Ghost has shut down
[2022-08-01 14:17:04] WARN Ghost was running for a few seconds 
``` 

The error message was not very enlightening.

**Solution**

The issue was using port 80. Dont use `server__port=80` . Stick to the default port `2368` and redirect via docker or any reverse proxy.
There is no other process running in the docker container, which could block the port, so i have no good explanation why port 80 is not accepted.
A better error message would be great :)

**Comment by pascalandy** [comment]
Great finding! You should propose this here - https://forum.ghost.org/c/ideas/5

**Comment by markstos** [comment]
It would be great if Ghost could provide a better error message here. Until they do, this page is a top result for searching for the issue, and I can explain what's likely happening a bit further. 

The Ghost container follows the security best practice of not running as root-- it runs as UID 1000. Inside the container, that maps to the `node` user. You can confirm this with a `sudo ps | grep node`.  You'll see the result is not running as root. 

You might be surprised to see it's running as /your/ user and not `node`. That's because if you have the first account on your system, your account was likely created with UID 1000 on the host. By default, containers share the same UID namespace with the host, so UID of 1000 within the container equals the UID of 1000 on the host. 

The root cause here has to do with a Unix-ism which is perhaps outdated in the age of containers-- non-root users are not allowed to bind to "privileged ports", which are defined as those with numbers less than 1024. This lore is explained here:

https://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

So when the `node` user within the container attempts to bind to port 80 within the container, it fails even though the container is not running anything else on port 80.

**Comment by markstos** [comment]
Title could be updated to be "Ghost won't start on port 80 or 443. Error -13".
