### ISSUE TITLE
Custom Port

### ISSUE THREAD

**Issue by petuniapetals** [docker-library/ghost#376]
I am trying to run the $ docker run -d --name some-ghost -e NODE_ENV=development -e url=http://localhost:3001 -p 3001:2368 ghost

However, everytime i key in the docker run file i get the message  

Error response from daemon: Conflict. The container name "/some-ghost" is already in use by container "65280a0e6ad2f144cfc512b75b9c5f231a2e8cb6d3528f6db622c0c94fe71c41". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

**Comment by wglambert** [comment]
Do `docker ps -a` to see all "stopped" containers that are still holding their container name and any port bindings. Then you can `docker rm -f some-ghost`

In the future questions like these are better asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
