### ISSUE TITLE
Working on a build for Ghost 1.0

### ISSUE THREAD

**Issue by pascalandy** [docker-library/ghost#65]
Hello Folks!

I love the work Docker is doing for Ghost. It's super easy run and update from version to version. The official image is great!

I tried to build Ghost [1.0.0-alpha.21](https://github.com/TryGhost/Ghost/releases/tag/1.0.0-alpha.21) and I could not run Ghost successfully :-\

Wondering if someone have found a way to run the alpha version in Docker.

Cheers!

**Comment by tianon** [comment]
Great idea -- took the first step over in https://github.com/docker-library/ghost/pull/66.

**Comment by tianon** [comment]
Looks like https://github.com/TryGhost/Ghost-CLI is going to be the "canonical" installation method for 1.0 (see http://support.ghost.org/v1-0-alpha/, especially "when we ship Ghost 1.0 this will be **the** way to install and update Ghost"), and it wants to manage installations in a bit of an interesting way (so it can handle upgrades, etc).  Not 100% sure how to handle this best via Docker yet.

Might be that the Docker images for 1.0+ only include `ghost-cli`?  Maybe some scripts to handle the common cases?  Not sure yet.

**Comment by tianon** [comment]
`ghost-cli` appears to be intended to manage the full lifecycle of the Ghost instance (`ghost start`, `ghost stop`, `ghost restart`, `ghost update`, etc), which is kind of a problem for Docker usage.  Perhaps we should file an issue over there to see if they're willing to advise on what we should do WRT Docker for 1.0+. :innocent: :sweat_smile:

**Comment by tianon** [comment]
For reference, here's the very basic `Dockerfile` I've been testing with so far:
```dockerfile
FROM node:6-alpine

# grab su-exec for easy step-down from root
RUN apk add --no-cache 'su-exec>=0.2'

ENV GHOST_CLI_VERSION 1.0.0-alpha.17

RUN set -ex; \
	yarn global add "ghost-cli@${GHOST_CLI_VERSION}"

ENV GHOST_SOURCE /usr/src/ghost
WORKDIR $GHOST_SOURCE
```

**Comment by pascalandy** [comment]
Thanks for sharing this http://support.ghost.org/v1-0-alpha/#testing-ghost-alpha-with-the-new-installer, will take a look :)

**Comment by pascalandy** [comment]
Hi @tianon. I found fixer on [slack](https://ghost.slack.com/team/fixer) and he managed to make Ghost Alpha work on his setup. It’s not perfect but it can guide us.

```
Well my setup has multiple weak points. A) downloads lateat alpha from an url generated by my api (wrapper for github api)

So as ive said earlier its a quick & dirty kind of thing

Also the way im using env vars is a little messed up because of my current setup (using the image on heroku,openshift & local dev cluster

Its still good enough for testing  but i dont tudod nk its good enough for the official image
```

#### Dockerfile

https://hub.docker.com/r/fixer/ghostfixer/builds/bsuiay8cvngcmmklj4qzko5/

and start.bash [file](https://gist.github.com/pascalandy/cdb329a7736150c26a3918e9986a8517) 

#### Easy try out!

```
docker run -d --name=ghostalpha -e PORT=2368 -p:2368:2368 fixer/ghostfixer:alpha
```

**Comment by pascalandy** [comment]
Here is plain installation (not a Dockerfile) for Alpine. 
Ghost runs but I can't connect when I go to localhost:2368

I guess this logic is too simple a full Dockerfile but if it can help other folks to start here it is :)

```
# Run Node container
docker run -dit --name GhostAlpineWIP \
-p 2368:2368 \
node:6-alpine sh && \

# Connect into Node container
docker exec -it GhostAlpineWIP sh;

# Basic updates and installs
apk update && \
apk upgrade && \
apk add curl && \

npm install -g ghost-cli && \
mkdir ghostapp && \
cd ghostapp && \
ghost install local && \

# Check the installation
ghost --version && \
ghost ls && \
ghost log ghost-local && \
curl localhost:2368

# Remove Container
# exit then...
docker rm -f GhostAlpineWIP
```

**Comment by noahwhite** [comment]
I am trying to Dockerize 1.0 beta-2 on Alpine and seeing the same behavior when running a local ghost install. 

I am guessing that when you run Ghost in local mode it only binds to localhost and thus you can't expose it outside the container.

**Comment by noahwhite** [comment]
That was the issue for me and I got it to work by adding `--ip 0.0.0.0` too `ghost install local`

**Comment by pascalandy** [comment]
Cool!! I'll try this :)

> I got it to work by adding --ip 0.0.0.0 too ghost install local

**Comment by magnonellie** [comment]
I probably shouldn't come in here and pretend like I know anything, but whatever.

I asked in the help chat on the ghost slack ([message link](https://ghost.slack.com/archives/C04CUS2R3/p1499720935290662)) and it seems like you can just install ghost the "normal" way (downloading the zip, npm i, npm start, etc) without any trouble if you're just aware about everything else that needs to go in there. I guess that would probably also end up being the easiest way for this project to pick up since it's essentially just what's here now, right? What probably needs to be done however is to add instructions on how to use this image in conjunction with the mysql one since [ghost is gonna use that by default in production](https://dev.ghost.org/alpha-8-mysql-default/).

**Comment by Windfarer** [comment]
Now ghost 1.0.0 has been released, any update for this docker image? @tianon

**Comment by tianon** [comment]
We definitely need to figure out how to handle Ghost 1.0, but I don't think we have a good answer for that ATM, and really need to talk to upstream to see whether they'd like us to do something based around the new `ghost` tool or whether they'd rather we continue to build this image the same way we have been (downloading the release and extracting it directly, which is the more "Docker-native" solution).

**Comment by tianon** [comment]
Alternatively we could swap this image to simply be `ghost:cli-X.Y.Z`, but I'm not sure whether that really adds much value -- we really need upstream's input to do this properly.

**Comment by SISheogorath** [comment]
A good place to look at is here: https://docs.ghost.org/docs/using-ghost-cli-programatically

**Comment by alexellis** [comment]
The "let's make a CLI to rule them all" approach is going to make running this in Docker hard. Here's how I did it - https://blog.alexellis.io/try-ghost-1-0-in-docker/

**Comment by alexellis** [comment]
There is also a kind of anti-container sentiment (maybe it complicates support?) It's a bit odd as I think the hosted product version runs on LXC. https://github.com/TryGhost/Ghost-CLI/issues/384#issuecomment-318430328

**Comment by acburdine** [comment]
@tianon FWIW I can create a recommended Docker setup based on what's here currently that also uses `ghost-cli`. (I built most of it so have a good idea of how to make it work well in Docker :wink:)

@alexellis it's not so much anti-container sentiment as it is trying to reduce Ghost's support overhead - if a docker install of Ghost has issues people come to Ghost support and previously, we tried to help which reduced the amount of time that we had to work on new features. With the new CLI - the intent was to support fully a recommended stack and then make the community provide support for other, non recommended stacks

**Comment by alexellis** [comment]
I guess you are aware that this approach makes Docker + Ghost even harder. (Being stateful vs effectively immutable, trying to manage the process itself, including systemd, including nginx, expecting Ubuntu 16.04). I can see how a known configuration would reduce support time and issues - but running applications in containers seems like a core use-case. Hopefully there will still be a sensible way to run with containers moving forward while taking advantage of the easier install afforded by the CLI.

**Comment by tianon** [comment]
@acburdine any help you're willing to offer would be amazing, and really appreciated!! :heart:

**Comment by acburdine** [comment]
@alexellis Like I said - I have a pretty good way of making it run right with docker, just need to fix a bug and I'll have a working setup 😄 

@tianon reading your comment above would definitely be willing to have a chat sometime about how best to move forward with Docker & Ghost-CLI - feel free to email and we can figure something out.

**Comment by SeerUK** [comment]
I like the idea of Ghost CLI, and it does seem to be a nice tool, but I must admit that as others have said above, I'm surprised at the lack of a truly container-friendly approach to running Ghost in this age of containers.

Personally, I'd like to just see some recommended installation instructions that don't use Ghost CLI. It's a nice tool, but to get Ghost successfully running in Docker myself in production mode / development mode as I want I've basically had to disable every feature Ghost CLI gives you, and just focus on having it download and extract Ghost, and create a configuration file. If there were just some instructions about how to initialise Ghost on it's own without Ghost CLI, that'd be a good starting point for easier containerisation. Maybe even some Ghost-in-container recommendations specifically, given that a LOT of people are running things in containers these days. I've still got an older instance of Ghost running in Docker elsewhere, and it's working great still - without the CLI.

Just to be clear, I don't want to make it sound like the CLI tool is pointless or a bad tool, because it isn't, and I am certain it'll be a huge boon to people who aren't Docker savvy, or simply don't want to run things in containers, etc. but right now, as the _only_ recommended way to install Ghost, it is really not Docker-friendly - and it feels like a huge oversight. Perhaps this situation will improve with more documentation about the CLI tool too.

Some ways this could be made more Docker friendly:

* Allow basic "download, extract, and set up to run without anything else at all happening, no user config, no DB config, no systemd, no checks, nothing" to be a bit simpler (`$ ghost install docker` or `$ ghost install bare`, etc.?) I know you can just disable all the things like I have for now - this one isn't actually a big deal, it'd just be nice to have this functionality abstracted behind a command.
* Allow configuration via environment variables when you run Ghost (e.g. via `$ ghost run`), e.g. switching environment, configuring your database, and configuring directories. This would be HUGELY beneficial compared to the current approach with the CLI, because as it's been explained above the current approach sort of makes you build configuration into your image... Allowing Ghost to be configured with environment variables would probably be the biggest step to make Ghost more Docker-friendly IMO.
* Another thing that would be nice to think about, I've not thought about it enough to give any suggestions yet, is how you'd update Ghost when it's running in a Docker container. Generally you'd update the image being used (i.e. again, not necessarily using Ghost CLI to run the update specifically - not without complicating things like automation at least), meaning things like your content and database would have to be migrated when the container starts (honestly, I'm not sure if this is already the case or not).

The aim would be to be able to make a container image that's immutable, and doesn't need to change in any way at build-time, but would respond to different configurations at run-time.

**Comment by jtcressy** [comment]
I'd like to point out that Ghost 1.0 currently supports *overriding* configuration with environment variables: https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables

However I think that documentation should be expanded upon. I also noticed that Ghost won't take the env vars unless they are *lowercase* such as ``database__connection__host`` instead of ``DATABASE__CONNECTION__HOST``

**Comment by acburdine** [comment]
PR is now open with configs for Ghost 1.0 😄 Turns out the bugfix wasn't needed after all! #67

**Comment by pascalandy** [comment]
Hi @acburdine ! 
Thanks for pushing this. It's very interesting to read your Dockerfile. I just build it. then run:

```
docker run -dit --name ghost \
-p 2368:2368 devmtl/dockerghost:latest
```

but got this error on my server and on my mac:

```
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH".
```

Something else we should know about running Ghost in a container?
Many cheers!

**Comment by acburdine** [comment]
Ah! Looks like I need to add execute permissions to a couple of the files. Will fix tomorrow morning :)

**Comment by tomkersten** [comment]
FWIW: I have taken a slightly different approach which uses the recommended stack (aside from systemd & nginx) and breaks MySQL and the Ghost app into separate containers. My setup/approach likely isn't for everyone, as it assumes you have set up `nginx` (+ SSL, etc) elsewhere...but it feels like it may end up working well for me so I thought I'd share for those interested...

https://github.com/tomkersten/ghost-docker

[Lots of room for improvement I'm sure...PRs welcome]

**Comment by alexellis** [comment]
I think you'll end up with a smaller image on Alpine Linux. Have you thought of using a stack instead of old compose v2? https://blog.alexellis.io/docker-stacks-attachable-networks/

**Comment by tomkersten** [comment]
@alexellis I assume you were talking to me...if not, ignore what follows....

I don't necessarily want to hijack this thread with ways of changing what I've done, unless others are interested (as my solution/approach is not a fork of this codebase at this point).

However, to answer your points:

> I think you'll end up with a smaller image on Alpine Linux.

Although I appreciate the sentiment, this was not really my concern, to be honest. I was primarily interested in getting as close to the "recommended stack" as possible without violating the fundamental "single process" approach to a container. I started with an Alpine Linux install and had it ~80% there, but switched to Ubuntu to be in line with the recommended stack (to simplify updates, etc). PRs or forks are welcome, of course...

> Have you thought of using a stack instead of old compose v2? https://blog.alexellis.io/docker-stacks-attachable-networks/

I had not. To be honest, I've never done anything with stack and didn't realize v2 of compose files was _that_ old (I'm definitely not a Docker expert). I was anxious to get a deployment that was functional, compatible, and easy to maintain with the `nginx-proxy` I have set up. Again, totally open to PRs...

**Comment by pmig** [comment]
@tomkersten Your stack would be ideal for me too, but I would also love to have to have to commitment for stability and up to date images of an official repository. Maybe we get the splitted images into the official repos with a different version tag and ensure that the image is concurrently build with the other one!

**Comment by alexellis** [comment]
Often the official images provide 2-3 alternatives - Ubuntu/fully bloated / Debian slim and Alpine. The example I shared above shows how to add Node.js to Alpine Linux. As for compose - stacks are in compose format 3.0 and the latest format is 3.1 which also supports secure secrets. Secrets could be useful for a MySQL container for instance.

I have been maintaining Ghost images for some time for x86_64 / ARM but would be more interested in seeing "official" Dockerfiles to point people at going forward.

**Comment by SeerUK** [comment]
If anyone is curious to see a (mostly complete) slightly different approach, using Alpine, avoiding the bulk of the system setup stuff, then I've made this image: https://github.com/SeerUK/docker-ghost I'd like to hear any criticisms anyone has regarding the image too.

**Comment by jwarkentin** [comment]
I generally like the approach @tomkersten has taken since I already have MySQL and nginx with SSL running separately. I suspect anyone using Docker will have a similar setup since that's kind of just the way things are done with Docker. An Alpine base would certainly be preferable though. Can this just be based on the Node.js Alpine image on Docker Hub?

Also, it would be really nice if it could run a script to check if it needs to run the `ghost update` command prior to starting Ghost as part of the run command. Then updating would be as simple as updating the Docker image and starting it. Not sure how to check if it needs to update though. Is the version stored in the DB or anything? Alternatively, is it bad to run the update command every time the container is started? Not sure what all it does.

**Comment by SeerUK** [comment]
@jwarkentin My image does indeed do a `ghost update` if the version you request is different to the detected installed version (it also detects if a new installation is needed if the installed version detected is empty).

This way you don't update the Docker image, but instead update an environment variable.

**Comment by jwarkentin** [comment]
@SeerUK Nice! I like that approach for managing installation and updates. I haven't ever used Docker for development personally so that won't affect me much. I generally use a scripted Vagrant environment for development. I'll have to look closer at your setup when I have some time but I like where it's going.

**Comment by pascalandy** [comment]
@jwarkentin I don't think this is good practice.

> Then updating would be as simple as updating the Docker image and starting it.

You don't want to be surprised that Ghost have updated and that broken your theme or your DB.

**Comment by jwarkentin** [comment]
It's not really a surprise if you update the image tag you're pulling. But the environment variable update approach used by @SeerUK works too and may be better because it doesn't require a new image to update to the latest version. The only potential downside I see is if a new version of ghost changes how things work and actually requires an updated image to work.

Generally with Docker if I want to update something like Node.js, Elasticsearch, MySQL, etc... I change the tag to the version I want to run. And it's completely in my control so it's not a surprise either. And like with Elasticsearch, once you run it with the newer version it performs some updates on the underlying files and you can't go back so it's not like it's an unprecedented practice or anything. Regardless, I think both ways are fine. In either case you're just updating the version in your docker-compose file.

**Comment by pascalandy** [comment]
My bad. I should have quote:

>  would be really nice if it could run a script to check if it needs to run the ghost update command prior to starting Ghost as part of the run command.

When the container restart it could be update Ghost. We probably don't want this behaviour. Make sense?

**Comment by jwarkentin** [comment]
Right. I see what you're saying. Yeah, that would be bad if it just updated it to whatever the latest version is when the container started. Ideally, it'd be able to update to a specific version that the container was built for. I know the install command allows specifying a version but I didn't see anything in the docs that allows updating to a specified version so that might not be possible.

**Comment by pascalandy** [comment]
Just took a look at the code and Ghost 1.0 is Dockerized! Can't wait to try it :-p

**Comment by alexellis** [comment]
"Upgrading" code inside a container makes it stateful, that's not a good way to manage your data. Using a Docker volume might be better. https://blog.alexellis.io/keeping-shipping-your-blog/

**Comment by SeerUK** [comment]
@alexellis Correct, that's why my image doesn't do that. You specify a version as an environment variable, you would keep this as a static value (like you might some database credentials, etc.) and only change it if you want there to be a change.

My image stores the entirety of Ghost in a volume. There are no specific Ghost instance files kept in the image. Only Ghost CLI, and some scripts to automate the steps you might want to handle easily (like installing, updating, and starting Ghost).

This way, the image is immutable, and it would pretty much just change if you wanted to upgrade Ghost CLI. I was tempted to call the image `seeruk/ghost-cli`, but decided against it because the idea of the image is to run a Ghost instance, i.e. with the scripts included in the image too.

**Comment by pascalandy** [comment]
I confirm ghost 1.0 runs perfectly locally and on a server. See how [here](https://github.com/docker-library/ghost/issues/69#issuecomment-319741569).

Cheers!

**Comment by ColtonProvias** [comment]
Also confirming. Docs on hub.docker.com need to be updated to the new volume, though.

Now to start work on Dockerizing Ghost 1.4.0!

**Comment by pascalandy** [comment]
Will do a PR :)

> Docs on hub.docker.com need to be updated to the new volume, though.

Also, I'll leave the issue open for couple of days but so far I think we are good to go :)

**Comment by pascalandy** [comment]
My PR is out [here](https://github.com/docker-library/docs/pull/971). Looking for your feedback folks. I know I sound funny in english sometimes :-p

**Comment by pascalandy** [comment]
I confirm the images are running smoothly (since 2 days running 1.0.2).
This morning, just restarted the container using 1.5.0. Cheers!

**Comment by tianon** [comment]
Rock on! :+1:
