### ISSUE TITLE
How can I set an external database for Ghost 1.x

### ISSUE THREAD

**Issue by raccoonyy** [docker-library/ghost#71]
For now,
It looks like hard coded with sqlite3 in the `Dockerfile`.

**Comment by acburdine** [comment]
The default is sqlite3, yes, but in Ghost 1.0 you can configure your instance using environment variables - see the docs [here](https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables) for more information.

Closing this as hardcoded sqlite by default is intentional and it is possible to override.

**Comment by raccoonyy** [comment]
@acburdine Thank you for your reply. Your information has been a great help.
