### ISSUE TITLE
Add option to set the URL for the Ghost installation

### ISSUE THREAD

**Issue by Dexus** [docker-library/ghost#77]
Because of the localhost:2368 in the dockerfile, its bad...
let us use a ENV where we can set the URL.

**Comment by SISheogorath** [comment]
What version of ghost are you using?

If it's 1.0 or higher please see: https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables

**Comment by Dexus** [comment]
Yes its 1.5 but the Image overwrite it with the --url command...

**Comment by acburdine** [comment]
@Dexus going to close this because the idea is to pass in the environment variables on `docker run`, e.g. `docker run -e url=https://newurl.com -p 2368:2368 ghost:latest`.

If you're looking to overwrite it during `docker build`, you could do something like this inside your dockerfile:

```dockerfile
FROM ghost:latest
RUN ghost config url <yoururl>
CMD ["node", "current/index.js"]
```

**Comment by Dexus** [comment]
@acburdine sorry, but I run the command like `docker exec -it go-siris.com-ghost sh` and it dont work because you overwrite it with the `--url` command in the setup...

So I wish to set the ENV to make the -e functional...

**Comment by SISheogorath** [comment]
I can't confirm:
```
docker run -e url=https://newurl.com -p 2368:2368 ghost:latest 
Unable to find image 'ghost:latest' locally
Trying to pull repository docker.io/library/ghost ... 
sha256:7d741f89087baa9f9656acc283b376d63385d0c4e7b208fdee8b57dca8cccda1: Pulling from docker.io/library/ghost
ad74af05f5a2: Pull complete 
2b032b8bbe8b: Pull complete 
ad85906adb69: Pull complete 
3caae50f774b: Pull complete 
e16f9635110e: Pull complete 
13ce7d61369b: Pull complete 
5e670e0bbef3: Pull complete 
63aad050bd4e: Pull complete 
98e6de9cf862: Pull complete 
59c3128ab9f4: Pull complete 
Digest: sha256:7d741f89087baa9f9656acc283b376d63385d0c4e7b208fdee8b57dca8cccda1
Status: Downloaded newer image for docker.io/ghost:latest
[2017-08-10 19:10:22] INFO Creating table: posts 
[2017-08-10 19:10:22] INFO Creating table: users 
[2017-08-10 19:10:22] INFO Creating table: roles 
[2017-08-10 19:10:22] INFO Creating table: roles_users 
[2017-08-10 19:10:22] INFO Creating table: permissions 
[2017-08-10 19:10:22] INFO Creating table: permissions_users 
[2017-08-10 19:10:22] INFO Creating table: permissions_roles 
[2017-08-10 19:10:22] INFO Creating table: permissions_apps 
[2017-08-10 19:10:22] INFO Creating table: settings 
[2017-08-10 19:10:22] INFO Creating table: tags 
[2017-08-10 19:10:22] INFO Creating table: posts_tags 
[2017-08-10 19:10:22] INFO Creating table: apps 
[2017-08-10 19:10:22] INFO Creating table: app_settings 
[2017-08-10 19:10:22] INFO Creating table: app_fields 
[2017-08-10 19:10:22] INFO Creating table: clients 
[2017-08-10 19:10:22] INFO Creating table: client_trusted_domains 
[2017-08-10 19:10:22] INFO Creating table: accesstokens 
[2017-08-10 19:10:22] INFO Creating table: refreshtokens 
[2017-08-10 19:10:22] INFO Creating table: subscribers 
[2017-08-10 19:10:22] INFO Creating table: invites 
[2017-08-10 19:10:22] INFO Creating table: brute 
[2017-08-10 19:10:22] INFO Model: Post 
[2017-08-10 19:10:23] INFO Model: Tag 
[2017-08-10 19:10:23] INFO Model: Client 
[2017-08-10 19:10:23] INFO Model: Role 
[2017-08-10 19:10:23] INFO Model: Permission 
[2017-08-10 19:10:23] INFO Model: User 
[2017-08-10 19:10:23] INFO Relation: Role to Permission 
[2017-08-10 19:10:24] INFO Relation: Post to Tag 
[2017-08-10 19:10:24] INFO Relation: User to Role 
[2017-08-10 19:10:24] INFO Finished database migration! 
[2017-08-10 19:10:27] INFO Ghost is running in production... 
[2017-08-10 19:10:27] INFO Your blog is now available on https://newurl.com/ 
[2017-08-10 19:10:27] INFO Ctrl+C to shut down 
[2017-08-10 19:10:27] INFO Ghost boot 2.623s 
```

**Comment by EgoWumpus** [comment]
Fwiw, I was having the OP's problem when I executed this:

```
docker run --name my-blog -p 127.0.0.1:3001:2368 -v /var/ghost/content:/var/lib/ghost/content -e NODE_ENV=production -e GHOST_URL=https://www.my-blogs-url.com -d --restart unless-stopped ghost
```

But not when I modified that command and ran it like this:

```
docker run -it --rm --name my-blog -p 3001:2368 -v /var/ghost/content:/var/lib/ghost/content -e url=https://www.my-blog-url.com -e NODE_ENV=production -d ghost
```

In the former case the `url` environment variable seemed to be overwritten with `localhost:2368`, and clicking on any `@blog.url` links would yield an error (though the blog otherwise ran fine). In the latter case there was no such problem.

**Comment by rfelsburg** [comment]
It really should be called out that the url now has to be set from the docker run line, and not in the config.json. 

My config.json still has the url key populated, but since the jump to 1.x now fails. Just so we're clear, we can no longer set the url in the config.json, only on the docker run line with a "-e url=https://myblog.example"

Here's the snippet from my config.json.

```
// # Ghost Configuration
// Setup your Ghost install for various [environments](http://support.ghost.org/config/#about-environments).

// Ghost runs in `development` mode by default. Full documentation can be found at http://support.ghost.org/config/

var path = require('path'),
    config;

config = {
    // ### Production
    // When running Ghost in the wild, use the production environment.
    // Configure your URL and mail settings here
    production: {
        url: 'https://myblog.example',
```

**Comment by tianon** [comment]
The whole config format for 1.x is different, isn't it?

URL should be settable in the config, but you'll also need to copy some
bits from the configuration embedded in the image, so using environment
variables is definitely going to be simpler and less error-prone.

**Comment by SISheogorath** [comment]
Not only the config is different. Also the data format which means that when you upgrade from lts to stable, you should throw away your configs and data from your backend and start with a clean, newly setup 1.0 instance.

The Data for this instance you exported using the export function of the ghost-frontend's experimental section of your old instance and import it into your new instance. Also keep in mind to update your theme because there were some breaking changes.

**Comment by rfelsburg** [comment]
I've updated the theme already, unfortunately the documentation around setting custom configs leads to a 404 for the link: https://docs.ghost.org/docs/configuring-ghost#section-custom-configuration-files.

Can you point at documentation around how the new configuration file should be setup? I'm having the same problem with getting it to use mysql instead of sqlite.

**Comment by tianon** [comment]
Looks like it's moved to
https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables;
I'll go update the documentation now.

**Comment by tianon** [comment]
Oh, that is the link that the docs have. 😇

**Comment by tianon** [comment]
FYI, I've filed https://github.com/docker-library/docs/pull/1306 to help clarify this. :+1:

**Comment by yussenn** [comment]
when you use a https with a domain, you need to add the header to your web server, by example in nginx:
 proxy_set_header   X-Forwarded-Proto $scheme;

**Comment by Blockost** [comment]
> when you use a https with a domain, you need to add the header to your web server, by example in nginx:
> proxy_set_header X-Forwarded-Proto $scheme;

Sir, you're the real MVP!

**Comment by trabur** [comment]
it seams like some parts of the application use this env var URL and some parts do not. for my particular setup when i set it to http://localhost:3000 the app works. however not all links in the UI work. then when i set this value to my https://blog.mysite.com production url my browser redirects me to http://localhost:3000 when trying to load the page.
