### ISSUE TITLE
Docker container stops after start. File problem?

### ISSUE THREAD

**Issue by vicaba** [docker-library/ghost#87]
Hello,

I was using version 0.11 starting and stopping the container whenever I needed to blog, with a shared folder with my computer.

I'm trying to upgrade the version to 1.8.1 but I am having some trouble. I have managed to start the container the first time, `docker run -d --name blog -p 2368:2368 -v /Users/vicaba/Projects/my_journal_blog2:/var/lib/ghost/content ghost:1.8.1`. Everything works go to the corresponding url localhost:2368. But I have noticed that the container stops if the directory `/Users/vicaba/Projects/my_journal_blog2:/var/lib/ghost/content` is already created by me when I issue the previous command.
Also, when I stop the container `docker stop blog` I have noticed that file/direcory permissions are appended with an `@` symbol (I am using a Mac) and running `docker logs blog` shows, among the usual http server output, the following line `chown: changing ownership of '/var/lib/ghost/content/themes/casper': No such file or directory`. I have changed permissions to 777 recursively just in case, and I have also removed to `@` symbol issuing `sudo xattr -rc ~/dir-to-fix` but it displays this line: `xattr: No such file: my_journal_blog2/themes/casper` . I think the problem is related with this file because it is a link that doesn't point to any file. Any suggestions on how to fix this?
This problem doesn't happen in version 0.11, as `casper` is a folder containing the template.

**Comment by yosifkit** [comment]
The casper symlink should point to a directory in the container so that the default theme can be updated outside of your blog files.  In `0.11` `themes/casper` contained the full theme files.

```console
$ # jumping in running ghost 1.x container
$ docker exec -it ghost bash
root@dd9f5ed828bf:/var/lib/ghost# ls -l content/
total 20
drwxr-xr-x 2 node node 4096 Sep 14 18:12 apps
drwxr-xr-x 2 node node 4096 Sep 15 22:53 data
drwxr-xr-x 2 node node 4096 Sep 14 18:12 images
drwxr-xr-x 2 node node 4096 Sep 15 22:53 logs
drwxr-xr-x 2 node node 4096 Sep 14 18:13 themes
root@dd9f5ed828bf:/var/lib/ghost# ls -l content/themes
total 0
lrwxrwxrwx 1 node node 44 Sep 14 18:12 casper -> /var/lib/ghost/current/content/themes/casper
```

Does the container not start the second time?  What is in your `/Users/vicaba/Projects/my_journal_blog2` directory?  Are you using "Docker for Mac" or docker-toolbox?  Any other information that might help?

**Comment by fernandesayla** [comment]
I'm facing the same problem! I can't start the Ghost on docker becouse the casper symbolic link... How can I fixit?

**Comment by tianon** [comment]
@fernandesayla you'll need to ensure the symlink stays intact (and if you're bringing your own `content` directory, you'll need to ensure the symlink exists within it, which the image entrypoint should also be helping do):

https://github.com/docker-library/ghost/blob/6ebc6712a201c82c039e81c55ca58b67aa1f2033/1/debian/docker-entrypoint.sh#L11-L19

Since this is more of a request for deployment help than an issue with the image, I'm going to close it.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
