### ISSUE TITLE
Add sendmail service

### ISSUE THREAD

**Issue by kdelfour** [docker-library/ghost#9]
I would like to know why you don't integrate sendmail service to docker ghost container. It will help you to minimize the config modification.

You can integrate  this in your config.

    mail: {
      transport: 'SMTP',
      options: {service: 'sendmail',}
    },

**Comment by tianon** [comment]
The discussion in https://github.com/docker-library/wordpress/issues/30 is important here too, since email is still a huge general problem that isn't solved in a good general way for Docker users yet.

**Comment by jrub** [comment]
I guess this depends on the library Ghost uses to send emails, nodemailer. In fact, they have a common place where all common email services have their configuration: https://github.com/andris9/nodemailer-wellknown/blob/master/services.json I don't see there sendmail, though.

**Comment by pascalandy** [comment]
I use Mailgun. Just pass the env-var when launching your container :)

mail: {
            transport: 'SMTP',
            options: {
                service : process.env.EMAIL_SERVICE,
                auth: {
                    user: process.env.EMAIL_USER,
                    pass: process.env.EMAIL_PASSWORD
                }
            }
        },

IMHO, we should close this issue.

**Comment by zicklag** [comment]
Could what @pascalandy mentioned be worked into the official image so that you could configure mail through environment variables?

**Comment by SISheogorath** [comment]
in >=1.0 it's no longer needed. See https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables

For >1.0 I don't think there will be a change in the current handling

**Comment by rucuriousyet** [comment]
@SISheogorath How can mail be configured via environment var? I am hoping to use Mailgun and I am having trouble finding anything helpful in the docs for Ghost or this Docker image. Any help you can offer up would be greatly appreciated!

**Comment by tianon** [comment]
@rucuriousyet combining https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables with https://docs.ghost.org/docs/mail-config#section-mailgun:

```bash
$ docker run ... \
    -e mail__transport=SMTP \
    -e mail__options__service=Mailgun \
    -e mail__options__auth__user=postmaster@example.mailgun.org \
    -e mail__options__auth_pass=1234567890 \
    ...
```

**Comment by davimello28** [comment]
@tianon Does your answer still works? I was trying to use it, but without success :(

 `docker exec container env` shows that the `env` was correctly there...

![image](https://user-images.githubusercontent.com/3607502/40900819-d32cd454-67a3-11e8-9dfc-adec92815266.png)

..but my `config.production.json` remains with the default values as shown below.

![image](https://user-images.githubusercontent.com/3607502/40900921-4c59e862-67a4-11e8-868d-9d571bfc40a6.png)

I also corrected the missing `_` on `auth__pass`. 

PS: I noticed a warning about port 25 traffic. My servers normally run on "paranoid" mode, but I suspect that it has nothing to do with it since the `config.production.json` stays intact.
