### ISSUE TITLE
Ghost docker on unRAID: URL variable does not persist across updates

### ISSUE THREAD

**Issue by vurtomatic** [docker-library/ghost#94]
Hi! I'm running Ghost as a docker on unRAID.

In my setup, I have /var/lib/ghost/content mapped to /mnt/user/appdata/ghost.

I've never been able to map the Ghost config folder (/var/lib/ghost/) to an unRAID share, I tried but Ghost wouldn't start.

Maybe because of that, every time the Ghost docker is updated, the URL variable in config doesn't persist. Always reverts to the default of http://localhost:2368/.

How can I have my custom URL persist?

(And how can I map the config folder to an unRAID share so it's easier to access Ghost config files instead of having to shell into the docker?)

**Comment by tianon** [comment]
Use an all-lowercase "url" environment variable and it should apply
properly (see the docker-compose example in the image description for a
link to the documentation about configuring via environment variables).

**Comment by vurtomatic** [comment]
@tianon  thanks for replying. Sorry I'm a noob so pardon my confusion.

I've already managed to change the url variable via the Ghost config CLI 

`ghost config url https://example.net/blog/`

The problem I'm encountering now is every time the Ghost docker is updated, the url defaults back to the original.

**Comment by tianon** [comment]
Yeah, use `-e url=https://example.net/blog/` on your `docker run` line (or add the `url` environment variable to the `environment:` section of your `docker-compose.yml` or `stack.yml`).

**Comment by tianon** [comment]
(Instead of using `ghost config url ...`)

**Comment by vurtomatic** [comment]
Sorry I see what you mean now.

I'm not building the docker myself, I'm using a Web GUI on unRAID, like this: https://imgur.com/a/IpHjW

**Comment by tianon** [comment]
Ok, then you'll need to figure out how to tell unRAID to add environment variables to the container -- that "Advanced Settings" section looks promising, but I've never heard of unRAID before now so I can't really suggest much more; sorry!

Since this isn't really an issue with the image that we could fix, I'm going to close this.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Thanks! :+1:
